name: Build PhD thesis and release

# Controls when the workflow will run
on:
  # Triggers the workflow on pushing new tags
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
            fetch-depth: "0"
      - name: Generate all chapters
        env:
          CHAPTERS: 1 2 3 4 5 6 7
        run: for c in $CHAPTERS; do sed "s/% \\\\includeonly{chapters\/1\/main/\\\\includeonly{chapters\/$c\/main/" main.tex > chapter$c.tex ; done
      - name: Get the main.tex from the last tag
        run: |
          git --version
          echo "${{github.ref_name}}"
          prevtag=$(git describe --abbrev=0 --tags "${{github.ref_name}}^")
          echo $prevtag
          git show $prevtag:./main.tex > mainprev.tex
      - name: Get the standalone current and previous main.tex
        run: |
          python3 expandmacros.py main.tex > mainexp.tex
          python3 expandmacros.py mainprev.tex > mainprevexp.tex
      - name: Diff the current and previous tag
        run: |
          chmod +x latexdiff-so
          ./latexdiff-so mainprevexp.tex mainexp.tex > diff.tex
      - name: Compile main LaTeX document and individual chapters
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            main.tex
            diff.tex
            chapter1.tex
            chapter2.tex
            chapter3.tex
            chapter4.tex
            chapter5.tex
            chapter6.tex
            chapter7.tex
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            main.pdf
            diff.pdf
            chapter1.pdf
            chapter2.pdf
            chapter3.pdf
            chapter4.pdf
            chapter5.pdf
            chapter6.pdf
            chapter7.pdf
