name: Build PhD thesis and release

# Controls when the workflow will run
on:
  # Triggers the workflow on pushing new tags
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
            fetch-depth: "0"
      - name: Generate all chapters with diffs
        run: |
          chmod +x generate_chapter_diffs.sh
          ./generate_chapter_diffs.sh
      - name: Compile main LaTeX document and individual chapters
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            main.tex
            chapter1diff.tex
            chapter2diff.tex
            chapter3diff.tex
            chapter4diff.tex
            chapter5diff.tex
            chapter6diff.tex
            chapter7diff.tex
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            main.pdf
            chapter1diff.pdf
            chapter2diff.pdf
            chapter3diff.pdf
            chapter4diff.pdf
            chapter5diff.pdf
            chapter6diff.pdf
            chapter7diff.pdf
